docs: add tarrer project as user of goreleaser-xx
crazy-max/goreleaser-xx pull request #75
Opened 2021-12-24 06:48 UTC by pratikbalar

One request also, can you check tarrer's  [Dockerfile](https://github.com/pratikbalar/tarrer/blob/main/Dockerfile) for me please to check are those `--mounts` are correctly configured to utilize caching?

2021-12-24 15:43 UTC, crazy-max commented
@pratikbalar 

> One request also, can you check tarrer's [Dockerfile](https://github.com/pratikbalar/tarrer/blob/main/Dockerfile) for me please to check are those `--mounts` are correctly configured to utilize caching?

SGTM but I would not recommend using UPX. Not just for the risk of producing false-positives from heuristic anti-virus software but also because it can cause unexpected memory behavior. Before choosing this kind of tool, you must be sure of its real added value for your project. From my pov, there is no real need to use it nowadays.

2021-12-24 15:47 UTC, crazy-max requested changes

2021-12-24 15:47 UTC, crazy-max commented on README.md
> +
remove this new line

2021-12-24 16:10 UTC, pratikbalar commented
> @pratikbalar
> 
> > One request also, can you check tarrer's [Dockerfile](https://github.com/pratikbalar/tarrer/blob/main/Dockerfile) for me please to check are those `--mounts` are correctly configured to utilize caching?
> 
> SGTM but I would not recommend using UPX. Not just for the risk of producing false-positives from heuristic anti-virus software but also because it can cause unexpected memory behavior. Before choosing this kind of tool, you must be sure of its real added value for your project. From my pov, there is no real need to use it nowadays.

But I think that's why I'm providing non-slim variant, Anyway I'll try to ignore it as much as possible. Thank you.

2021-12-25 17:25 UTC, crazy-max approved these changes

2021-12-25 17:25 UTC, merged